export const viaturas = [
  {
    id: 1,
    placa: "QNJ-1880",
    prefixo: "25854",
    lotacao: "45º BPM",
    unidadeFrota: "45º BPM",
    cidade: "PARACATU - MG",
    marca: "FIAT",
    modelo: "PALIO WEEKEND",
    ano: 2017,
    combustivel: "FLEX",
    odometro: 78215,
    situacao: "DISPONÍVEL",
  },
  {
    id: 2,
    placa: "QNJ-1890",
    prefixo: "25853",
    lotacao: "45º BPM",
    unidadeFrota: "45º BPM",
    cidade: "PARACATU - MG",
    marca: "FIAT",
    modelo: "PALIO WEEKEND",
    ano: 2017,
    combustivel: "FLEX",
    odometro: 80500,
    situacao: "DISPONÍVEL",
  },
];